import re
from app import db
from app.models.accusation import Accusation


class Trial(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    accusation_id = db.Column(db.Integer, db.ForeignKey(Accusation.id))
    trial_ref = db.Column(db.String(128))
    case_ref = db.Column(db.String(128))
    trial_type = db.Column(db.Integer)
    trial_settlement = db.Column(db.String(128))
    trial_parish = db.Column(db.String(128))
    trial_presbytery = db.Column(db.String(128))
    trial_county = db.Column(db.String(128))
    trial_burgh = db.Column(db.String(128))
    arrest = db.Column(db.Integer)
    arrest_date = db.Column(db.String(128))
    fled = db.Column(db.Integer)
    fled_date = db.Column(db.String(128))
    action_dropped = db.Column(db.Integer)
    action_drop_date = db.Column(db.String(128))
    action_dropped_by = db.Column(db.String(128))
    action_body = db.Column(db.String(128))
    confronting_suspects = db.Column(db.Integer)
    pretrial_notes = db.Column(db.Text)
    process_type = db.Column(db.String(128))
    trial_date = db.Column(db.String(128))
    trial_place = db.Column(db.String(128))
    female_accusers = db.Column(db.Integer)
    male_accusers = db.Column(db.Integer)
    high_status = db.Column(db.Integer)
    defence = db.Column(db.Integer)
    verdict = db.Column(db.String(128))
    sentence = db.Column(db.String(128))
    cjt_order = db.Column(db.Integer)
    cjt_date = db.Column(db.String(128))
    circuit = db.Column(db.Integer)
    circuit_name = db.Column(db.String(128))
    local_with_crep = db.Column(db.Integer)
    no_ref_to_central = db.Column(db.Integer)
    trial_notes = db.Column(db.Text)
    execution = db.Column(db.Integer)
    execution_method = db.Column(db.String(128))
    execution_date = db.Column(db.String(128))
    execution_place = db.Column(db.String(128))
    exec_settlement = db.Column(db.String(128))
    exec_parish = db.Column(db.String(128))
    exec_presbytery = db.Column(db.String(128))
    exec_county = db.Column(db.String(128))
    exec_burgh = db.Column(db.String(128))
    post_trial_notes = db.Column(db.Text)

    def __repr__(self):
        return 'Trial: {}'.format(self.id)
